inherit:
    - tiny.yaml

model:
    n_dims: 2
    n_positions: 11
    loss: mse

training:
    batch_size: 50000
    learning_rate: .1
    train_steps: 100

exp_name: signpair
out_dir: .
use_fullbatch: true
